# Generated by Django 3.0.3 on 2020-02-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='job',
        ),
        migrations.AddField(
            model_name='users',
            name='job',
            field=models.ManyToManyField(to='users.Jobs'),
        ),
    ]
