# Generated by Django 3.0.3 on 2020-02-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200227_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='fullName',
            field=models.CharField(default='fahad', max_length=200),
            preserve_default=False,
        ),
    ]
