# Generated by Django 3.0.3 on 2020-02-29 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_users_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='job',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.Jobs'),
            preserve_default=False,
        ),
    ]
