# Generated by Django 3.0.3 on 2020-02-29 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='users.Jobs'),
        ),
    ]
