# Generated by Django 3.0.3 on 2020-02-29 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200229_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Jobs'),
        ),
    ]
