# Generated by Django 3.0.3 on 2020-03-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_users_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='whatsApp',
            field=models.BooleanField(default=False),
        ),
    ]
